In [2]:
#Assignment 6:
# Import the Numpy and use the vader function. This takes 3 inputs
# numpy.vander(x, N=None, increasing=False)
# 1. Array, 2. No of columns but optional 3.Increasing or decreasing powers of colun
# Code for increasing lef to right
import numpy as np
x = np.array([1, 2, 3])
N = 3
np.vander(x, N,True)
 

array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

In [3]:
#Assignment 6:
# Import the Numpy and use the vader function. This takes 3 inputs
# numpy.vander(x, N=None, increasing=False)
# 1. Array, 2. No of columns but optional 3.Increasing or decreasing powers of colun
# Code for right to left
import numpy as np
x = np.array([1, 2, 3, 5])
np.vander(x, N, False)
 

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [4]:
#Assignment 6:
# Import the Numpy and column_stack function
# This takes the single dimentional array and converts to 2 dimentional array Beloe are differnt options in stack
# stack - Join a sequence of arrays along a new axis.
# vstack- Stack arrays in sequence vertically (row wise).
# dstack - Stack arrays in sequence depth wise (along third axis).
# concatenate - Join a sequence of arrays along an existing axis.
# hsplit - Split array along second axis.
# block - Assemble arrays from blocks.

np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)